apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-cdeep3m-cil-predict-$crop_id
spec:
  containers:
  - name: gpu-container
    image: registry.gitlab.com/matthew.madany/ncmir-prp:latest
    command: [ "/bin/sh" ]
    args: [ "-c", "wget -O - $user:$pass@https://cildata.crbs.ucsd.edu/cdeep3m/scripts/CDEEP3M_prp; perl CDEEP3M_prp --augspeed $augspeed --models $models $enhance $overlay $crop_id $model_doi" ]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 8Gi
      requests:
        memory: 8Gi
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: gpu-type
           operator: In
           values:
           - 2080Ti